### ISSUE TITLE
It shows an error whenever I run it

### ISSUE THREAD

**Issue by Herobrine2008** [amitxv/AutoGpuAffinity#10]
Hello anyone please help me. The error shows this. Pls copy paste this link in a new tab.

![showing error](https://user-images.githubusercontent.com/127172974/223319421-cbc8d340-5e95-48a0-8203-2972f112b7d9.PNG)

**Comment by Herobrine2008** [comment]
> Duplicate of #9

what do you mean by that and can you please tell me how to solve it

**Comment by DB2555** [comment]
Yo @Herobrine2008 I have the same problem I have found no solution…
