### ISSUE TITLE
All FPS values are 0

### ISSUE THREAD

**Issue by miyatatakeshi** [amitxv/AutoGpuAffinity#11]
![image](https://user-images.githubusercontent.com/75170571/224576987-3d64864d-6acb-46e2-9479-20066ea93741.png)

**Comment by amitxv** [comment]
This was due to a compiler error with Cython. This was fixed a few days ago, re-download the latest release. Apologies.

**Comment by miyatatakeshi** [comment]
my bad, I thought I was using the latest version. thanks for the answer.
