### ISSUE TITLE
Interrupt

### ISSUE THREAD

**Issue by Nikitos18667** [amitxv/AutoGpuAffinity#13]
when I launched your program, the video card was transferred to the second core and after that I went into the game to check and my FPS dropped very much, please tell me what to do, I already stopped Windows, I changed the video card, set the core to zero, what else do I need to do

**Comment by amitxv** [comment]
The only variable the program changes is the GPU driver affinity which gets reverted to the Windows default (no affinity) after the program has finished benchmarking all CPUs. If for whatever reason it crashed while benchmarking and the affinity did not reset, you need to delete the mask in registry to revert the changes, nothing else.
