### ISSUE TITLE
Black screen after testing few cores -- solution

### ISSUE THREAD

**Issue by lolfaqgs** [amitxv/AutoGpuAffinity#14]
So after running the program a few times and getting black screen like 5 times in a row(black screen after few cores/sometimes even one core) i decided to check my bios
Turns out the problem was that my PCIE speed was set to "Auto" instead of "Gen3"
After setting it to "Gen3" i had no issues running the test like 10+ times in the row with no black screens@crashes
Then just to confirm it i set it to auto again and got couple of black screens again

**Comment by amitxv** [comment]
Thanks, i'll add a note in the README
