### ISSUE TITLE
CPU in results not in order

### ISSUE THREAD

**Issue by SnowzNZ** [amitxv/AutoGpuAffinity#15]
![image](https://github.com/amitxv/AutoGpuAffinity/assets/98007575/69f71191-7501-442f-8b4d-4ffa5c8b8766)

**Comment by amitxv** [comment]
Fixed in https://github.com/amitxv/AutoGpuAffinity/commit/1a0dbb7d504d63be6bc212b60b4a3cd90026cd4e. Thanks
