### ISSUE TITLE
Issue using autogpuaffinity

### ISSUE THREAD

**Issue by OneShotCS** [amitxv/AutoGpuAffinity#16]
When i run the application, it does load, but it never pops up the liblava (triangle thing) and says this message after.
![Screenshot 2023-06-26 124155](https://github.com/amitxv/AutoGpuAffinity/assets/96710669/62ecb761-6af5-4904-a4ed-2c7f8f678ddb)

**Comment by amitxv** [comment]
If lava-triange does not open then the issue is not related to AutoGpuAffinity
