### ISSUE TITLE
error after first iteration

### ISSUE THREAD

**Issue by YoBii** [amitxv/AutoGpuAffinity#18]
I get the same error other people are getting e.g. #16.

However something that I wanted to add. Although saving .etl is disabled in config and the tool confirms this before trying to run the benchmark I get a kernel.etl file written to my C root dir. 

Additionally it's not clear from the main page here which components of ADK have to be installed. I just installed the one component containing xperf (Windows Performance Toolkit). That should be sufficient, yea?

**Comment by amitxv** [comment]
Is the error you are experiencing the same in #16? As the comment suggests, not being able to launch lava-triangle is a problem independent to AutoGpuAffinity. You can try change the subject in the config alternatively.

I will check whether kernel.etl is generated in C:\ with tracing disabled soon.

**Comment by amitxv** [comment]
``C:\kernel.etl`` does not get generated for me with ``enabled=false`` in the config. Are you sure it isn't from a previous run?

**Comment by YoBii** [comment]
The console output was exactly like in issue #16 but lava-triangle did ran once.


**However** I can't reproduce this anymore. Neither the *csv log unsuccessful* error nor the kernel.etl in my C drive.
Works perfectly now. The only thing I changed was uninstalling my graphics drivers with DDU and installing current version (stripped down). So apparently that's what did it? Or maybe a reboot after installing ADK or rather Windows Performance Toolkit. Idk.
