### ISSUE TITLE
Short or long benchmarks?

### ISSUE THREAD

**Issue by kul-sudo** [amitxv/AutoGpuAffinity#19]
Hello!
Should I set the benchmark duration to a low or high value for the most trustworthy results? The reason why I'm not sure is this: when the benchmark duration is low, there's less room for just one frame which is a bit better or a bit worse than the other ones, but when the benchmark is long, I can imagine it is more similar to the tasks the GPU usually deals with, because they're long.

**Comment by amitxv** [comment]
Longer is preferred.
