### ISSUE TITLE
How to use the --apply?

### ISSUE THREAD

**Issue by saifalrifaie** [amitxv/AutoGpuAffinity#21]
HOW TO FIX THIS ISSUE 👇

THE PROBLEM:
Analyze Old Sessions
Accidentally exited the program after the results' table was displayed? Don't worry, you can analyze the CSV logs again at any time by passing the folder of CSVs to the --analyze argument (example below).

THE EXAMPLE IS WRONG:
AutoGpuAffinity --analyze "captures\AutoGpuAffinity-170523162424\CSVs"

I open cmd as an administrator and then write this:

AutoGpuAffinity --analyze "C:\Users\LALALALA\Downloads\AutoGpuAffinity\AutoGpuAffinity\captures\AutoGpuAffinity-111223021626\CSVs"

but it print this "AutoGpuAffinity' is not recognized as an internal or external command, operable program or batch file."

btw there is no start.bat file like what people have in the videos idk if you removed it or not.

THE SOLUTION (I used chat gpt): 
1. Go to the tool folder
2. Right click on the program itself
3. Click properties
4. In the General section there is location
5. Hover your mouse over it and copy
6. Now press on windows search icon
7. Write cmd and press "Run As Administrator"
8. Write "cd" the press space
9. Press Control ("crtl "on your keyboard) V to paste
 the location you copied
10. Now go to the captures section
11. Find the correct folder with exel record files in it 
12. Press on the file then CSVs
13. Up in the ribbon press to the right of the word CSVs
14. Copy the path
15. In cmd after doing step 9 now write "AutoGpuAffinity -- analyze " then paste the path you just copied.
16. It should popup now

EXAMPLE:
"cd C:\Users\LALALALA\Downloads\AutoGpuAffinity\AutoGpuAffinity
AutoGpuAffinity --analyze "C:\Users\LALALALA\Downloads\AutoGpuAffinity\AutoGpuAffinity\captures\AutoGpuAffinity-111223021626\CSVs"

**Comment by xSliver** [comment]
yo LALALALA,
consider the following lecture:
https://en.wikipedia.org/wiki/Path_(computing)
https://en.wikipedia.org/wiki/Working_directory
https://en.wikipedia.org/wiki/Command-line_interface
https://en.wikipedia.org/wiki/Computer_program

btw: your post is astonishing. I've never seen something like this, I could have never imagined anything like this. Your error message "AutoGpuAffinity' is not recognized as an internal or external command, operable program or batch file." is totally right. It seems to be a huge layer 8 problem, you're not going to fix this 4sure. Please do not provide ChatGPT solutions which you do not understand.

**Comment by saifalrifaie** [comment]
It worked tho Lmao

**Comment by amitxv** [comment]
The example is correct. You didn't CD into the folder.
