### ISSUE TITLE
Problem with cmd

### ISSUE THREAD

**Issue by FloEzV3** [amitxv/AutoGpuAffinity#23]
Good day. I have encountered such a problem that at a random moment of the test (can be from the very first (0) kernel or at the very end) the command line hangs with the inscription "not responding" And what is strange, cmd just becomes empty (as if the console is cleared and hangs). Can you tell me what could be the problem? And thank you very much for your time <3

**Comment by amitxv** [comment]
I haven't heard of this before. Have you tried PowerShell?
