### ISSUE TITLE
Virus !!!!!!!!!

### ISSUE THREAD

**Issue by JABSOL** [amitxv/AutoGpuAffinity#25]
https://www.virustotal.com/gui/file/59d3aae26816e2498364dda820515a9a4f5dc5b80ed546e2294cebf73e5a7a27/detection

**Comment by amitxv** [comment]
These are false positives due to pyinstaller: https://github.com/pyinstaller/pyinstaller/issues/6754. The binary is also built with GitHub actions: <https://github.com/amitxv/AutoGpuAffinity/blob/main/.github/workflows/release.yml>.

Alternatively, you can run the program from source.
