### ISSUE TITLE
ERROR: csv log unsuccessful, this may be due to a missing dependency or windows component

### ISSUE THREAD

**Issue by Krexc** [amitxv/AutoGpuAffinity#27]
How to fix this error? 
Cache Duration           10
Benchmark Duration       25
Benchmark CPUs           All
Estimated Time           0:03:00
Estimated End Time       12:01:18
Load Afterburner         False
DPC/ISR Logging          False
Save ETLs                False
Window Mode              Fullscreen (1920x1080)
Sync Affinity            False

info: press enter to start benchmarking...
info: benchmarking CPU 0
error: csv log unsuccessful, this may be due to a missing dependency or windows component
info: press enter to exit

**Comment by amitxv** [comment]
This is due to PresentMon not logging to a CSV file. There could be several reasons for this, the error is not directly related to AutoGpuAffinity. You can try on a fresh Windows OS in case the error is caused by something you have changed in your current OS.
