### ISSUE TITLE
Hi some error about not restarting driver

### ISSUE THREAD

**Issue by xodius80** [amitxv/AutoGpuAffinity#3]
I get a fail to restart graphic driver, installed the SDK. I don't know
![Untitled](https://user-images.githubusercontent.com/105532045/168410049-fb2bda9e-2833-4218-9ccb-0eefba0ab08d.png)
 what to do

**Comment by amitxv** [comment]
I see you are on a portable device, do you have a dedicated GPU or are you only using an integrated GPU?

**Comment by xodius80** [comment]
Nvidia Quadro 1000m on a hp 8560w EliteBook Intel video is deactivated by hardware

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by xodius80** [comment]
Thanks for the tool man, on my  x5600,Rx 470 (desktop) runs like a charm.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by amitxv** [comment]
The program was not intended for laptop GPU's anyway, i've generally seen people have a hard time with restarting the iGPU/dGPU driver on portable devices.

**Comment by xodius80** [comment]
I see but, negative, this laptop igpu is hardlocked deactivated on this cpu and laptop model.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
