### ISSUE TITLE
Hi, I need some help...

### ISSUE THREAD

**Issue by DB2555** [amitxv/AutoGpuAffinity#9]
I get an error message when I try to run the .bat - it says on the releases section 'Remove output path if error occurs during the benchmark' but I am not too sure on how to that... Can someone help me? @amitxv

**Comment by amitxv** [comment]
You misunderstood. That note in the release means that **the program** will remove the output directory if an error occurs .

Can you send a picture or more details of your error?

**Comment by DB2555** [comment]
Alright will do later on in the day…

**Comment by DB2555** [comment]
Here look I jst ran the bat file again and I have the same issue...
![Capture](https://user-images.githubusercontent.com/126919436/222905136-cf957191-b190-43cd-8ff6-0f4ec444c942.PNG)

**Comment by DB2555** [comment]
@amitxv do u know a fix??

**Comment by amitxv** [comment]
This means that PresentMon was not able to log to the CSV and isn't really related to my tool. You should try run the program on  fresh installation of Windows since I know for a fact it works there.

**Comment by DB2555** [comment]
Do you know any other fixes? I just don’t want to lose all of my files and optimizations on my current install….
@amitxv

**Comment by amitxv** [comment]
I don't know what you've done to your OS so I can't help you. There's a good change that one of your "optimizations" is the cause for PresentMon not being able to log data.

**Comment by DB2555** [comment]
I think, if I am remembering correctly, I may have disable log collection through a registry key(value) that may be the issue - do you think so?

**Comment by DB2555** [comment]
I’ll see if I can enable that again( if I have disabled it ) and see if the issue persists.

**Comment by DB2555** [comment]
I have Windows Event along Service disable - I have enabled it again and the issue still persists…
